### ISSUE TITLE
Search page box replicates by making blank searches

### ISSUE THREAD

**Issue by Bevinsky** [R-a-dio/site#20]
I can get multiple search boxes on the search page like this: [asf](http://puu.sh/6IQxF.png)

It can be replicated like this:
1. Make a search for something
2. Jump to the front page
3. Go back to the search page and make a blank search
4. Jump to the front page
5. Go back to the search page

Congratulations, you have now accelerated your searching with parallel search boxes.

**Comment by ameliaikeda** [comment]
fix'd

**Comment by 9001** [comment]
That's amazing
