### ISSUE TITLE
Foul language used on submission page

### ISSUE THREAD

**Issue by Wessie** [R-a-dio/site#26]
There really is no need to use `Search first bitch`, `heads will roll`, `learn to tag your damn files` etc. 

Just using normal language should be fine, this just makes it look very childish

**Comment by astra-bright** [comment]
The blatant advertising for Papa John's Pizza on said page is also something that should be removed from this weeaboo internet radio station

**Comment by ameliaikeda** [comment]
We aren't professional.

**Comment by shizmob** [comment]
Correction: _you_ aren’t professional.

**Comment by astra-bright** [comment]
#shotsfired
