### ISSUE TITLE
Submitting random 30MB .dll file crashes submission handler.

### ISSUE THREAD

**Issue by Wessie** [R-a-dio/site#27]
`ErrorException:
htmlentities() expects parameter 1 to be string, array given (View: /home/hiroto/Dropbox/radio/app/views/layouts/navbar.blade.php) (View: /home/hiroto/Dropbox/radio/app/views/layouts/navbar.blade.php)`

**Comment by ameliaikeda** [comment]
This'll be a bug with echoing the status output. I'll need a copy of that DLL.

**Comment by astra-bright** [comment]
Submitting anything that's not a mp3 seems to crash it for me..

**Comment by ameliaikeda** [comment]
Fix'd (in the AJAX form), closing since I can fix the status message handling later.
