### ISSUE TITLE
WTB better unicode support

### ISSUE THREAD

**Issue by CrimsonVoid** [R-a-dio/site#47]
Searching for パパ、アイ・ラブ・ユー!! breaks the site. Error is

array (size=4)
  'error' => string 'Illegal string offset 'hits'' (length=28)
  'trace' => string '#0 /home/hiroto/Dropbox/radio/app/traits/Search.php(12): Illuminate\Exception\Handler->handleError(2, 'Illegal string ...', '/home/hiroto/Dr...', 12, Array)
#1 /home/hiroto/Dropbox/radio/app/controllers/Home.php(89): Home->getSearchResults('\xE3\x83\x91\xE3\x83\x91\xE3\x80\x81\xE3\x82\xA2\xE3\x82\xA4...')
#2 [internal function]: Home->anySearch('\xE3\x83\x91\xE3\x83\x91\xE3\x80\x81\xE3\x82\xA2\xE3\x82\xA4...')
#3 /home/hiroto/Dropbox/radio/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(231):'... (length=3269)

  'line' => int 12
  'file' => string '/home/hiroto/Dropbox/radio/app/traits/Search.php' (length=48)

**Comment by CrimsonVoid** [comment]
Searching for "()" throws a similar error

**Comment by ameliaikeda** [comment]
None of this is a unicode issue. It's Lucene failing to parse some punctuation
