### ISSUE TITLE
Queue page is paginated and pagination is sort of broken

### ISSUE THREAD

**Issue by Bevinsky** [R-a-dio/site#49]
When the queue has more than a certain number of entries, it paginates. I don't think it should be paginated; the queue is never long enough to warrant it and it sort of hides results from people who are expecting the entire queue to be visible.

Also, the pagination seems to be broken. I don't have a screenshot, but when I spotted the pagination it was located to the right of the queue instead of below it.

Edit: Screenshot. ![](http://puu.sh/8AELR.png)

**Comment by ameliaikeda** [comment]
Queue hasn't been paginated for quite some time.
