### ISSUE TITLE
Linking to a comment in another news post doesn't work

### ISSUE THREAD

**Issue by astra-bright** [R-a-dio/site#59]
It won't do anything (for example here http://r-a-d.io/news/4#220 )

**Comment by ameliaikeda** [comment]
Works fine unless your browser doesn't understand fragments.

**Comment by astra-bright** [comment]
Doesn't work in Firefox 32 (Nightly), Firefox 29, Chrome, Browser (Android) or Safari (tablet).

Links to 4#56 when it should probably be linking to 2#56.

**Comment by ameliaikeda** [comment]
I literally can't replicate this; it's basic browser behavior (comments have `id="{{ $comment->id }}"`). What are you doing beforehand?

**Comment by astra-bright** [comment]
http://puu.sh/8KARN.gif

**Comment by Bevinsky** [comment]
The problem is not that the fragments are failing, it's that the comments are not on the same news page, so the fragment doesn't link anywhere. The comment links need to determine which news post the comment is on when they are created.
