### ISSUE TITLE
Queue page times are off after someone dj-ed

### ISSUE THREAD

**Issue by s4nji** [R-a-dio/site#60]
Screenshot: http://puu.sh/8JPHB.png
The times in the queue page are off after someone dj-ed.
This still occurs after the DJ is back to Hanyuu; newly requested song times are also off.

**Comment by s4nji** [comment]
Didn't notice the timezone; still an issue though.

**Comment by Wessie** [comment]
The website uses UTC as timezone, and currently there is no javascript to convert this to users local timezone. This is why the queue times **look** off on the website.

As for the `DJ -> Hanyuu` switch, the queue times will adjust themself when Hanyuu connects and starts streaming. This is currently not as instant as we intended so there will be a code change for that later.

**Comment by Wessie** [comment]
See issues #61 and [#1@radio.queue](https://github.com/R-a-dio/radio.queue/issues/1) for follow-up
