### ISSUE TITLE
Thread stuff missing

### ISSUE THREAD

**Issue by astra-bright** [R-a-dio/site#69]
While we haven't been on /a/ for some time, some DJs still link to other boards. If there's no thread fuction, there should be one, if it's already done it should be in the front page (preferably hidden by default).

**Comment by Wessie** [comment]
fix this already

**Comment by Kelarr** [comment]
^

**Comment by astra-bright** [comment]
https://github.com/R-a-dio/site/pull/78

**Comment by astra-bright** [comment]
ping
