### ISSUE TITLE
Clarify queue

### ISSUE THREAD

**Issue by gravufo** [R-a-dio/site#94]
The queue is very confusing. Some things appear as "x mins ago" and others as "in x mins" and the order varies often, so it's very inconsistent and hard to understand.

Here is an example:
![Image](http://puu.sh/syBQJ/f9281062c1.png)

As a user, I would expect the first thing in the queue to be the next played song, which is not the case here.
I would also ask myself what the heck "x mins ago" means for a song in the queue.

I might be totally off, but I just don't understand yet! Any clarification will be of much help to me and all the other users I think!

Thanks

**Comment by Bevinsky** [comment]
This has happened a couple times now. Server time is drifting for some reason, so timeago displays nonsense times in the queue. Happens for last played as well, at least on the front page.

**Comment by Bevinsky** [comment]
I'm pretty sure this is fixed now, it was a bug in the queue: https://github.com/R-a-dio/radio.queue/commit/db75d690ebbf6fa23cd5be5ee9d105e599cf39c2
