### ISSUE TITLE
Redo permission system

### ISSUE THREAD

**Issue by Bevinsky** [R-a-dio/site#98]
The single integer permission system is insufficient.

Currently, the permissions are as follows:
* 0: No permission
* 1: Can accept/reject/browse pending songs
* 2: Can connect to the proxy for djing
* 3: Can edit/create/delete news posts
* 4: Has admin access (can edit users/DJ profiles)
* 5: Has dev access (can see dev page in admin panel, can delete songs from the database)

This should be replaced with something more fine grained, represented by a pivot and definition table. 

The definition table is named 'permission_kinds'. It has 1 column.
* `VARCHAR(40) permission`: contains a permission name, all lowercase, no spaces. This is the primary key.

The pivot is named 'permissions'. It has 3 columns.
* `INT id`: ID. This is the primary key.
* `INT user_id`: FK to `users` table.
* `VARCHAR(40) permission`: FK to `permission_kinds` table.

A suggested list of permissions follows.
* `active`: Basic permission. Needed to log in and view the admin panel front page.
* `pending_view`: Can view the pending page and download songs.
* `pending_edit`: Can accept/reject pending songs.
* `database_view`: Can search the database.
* `database_edit`: Can edit and save database entries.
* `database_delete`: Can delete tracks from the database.
* `dj`: Can connect to the proxy and view/edit own DJ profile.
* `news`: Can create/edit/delete news posts.
* `admin`: Can create/edit/delete users, other users' permissions and other users' DJ profiles (with extra fields).
* `dev`: Can access the dev page.

**Comment by Wessie** [comment]
this look okay, we currently have 3 bits of code that touch these permissions so each one of them would have to be adjusted

**Comment by Bevinsky** [comment]
That's right, should mention which those are:
* site
* old hanyuu
* new hanyuu

Those are what you meant, right?

**Comment by Wessie** [comment]
they would be
- website
- new hanyuu
- icecast proxy

old hanyuu does not actually use permissions for anything

**Comment by Bevinsky** [comment]
Oh, right.

I'm planning to keep a stopgap by setting the old permission number for certain cases still, so anything that uses it will still work until it's updated.

**Comment by Bevinsky** [comment]
Halfway implemented now, only thing left is to adapt the database and pending pages +  navbar to properly use the new subpermissions.

**Comment by Bevinsky** [comment]
Done in 3ee2ec9f8747e7815b6a03934a8cfa8d2b51671e.
